
#### Cadastrar tarefa

POST http://localhost:5218/ListaDeTarefas/cadastrar/tarefa
Content-Type: application/json

{
    "nome" : "tarefa",
    "DescricaoTarefa" : "arrumar a cama"
}

#### Buscar tarefa

GET http://localhost:5218/ListaDeTarefas/buscar/tarefa/1cdc951d-e4fc-4ab6-bb19-4ce3d3d435c6

#### Listar tarefa

GET http://localhost:5218/ListaDeTarefas/listar/tarefa

#### Alterar tarefa
 
PUT http://localhost:5218/ListaDeTarefas/atualizar/tarefa/1cdc951d-e4fc-4ab6-bb19-4ce3d3d435c6
Content-Type: application/json

{
    "nome" : "tarefa teste 2",
    "DescricaoTarefa" : "arrumar a mesa"
}

#### Deletar tarefa
DELETE http://localhost:5218/ListaDeTarefas/deletar/tarefa/1cdc951d-e4fc-4ab6-bb19-4ce3d3d435c6