#### Cadastrar usuario

POST http://localhost:5218/ListaDeTarefas/cadastrar/usuario
Content-Type: application/json

{
    "nome" : "teste1",
    "cpf"  : "125.714.329-82",
    "genero" : "masculino",
    "email"  : "nicolas@gmail.com"
}

#### Buscar usuario

GET http://localhost:5218/ListaDeTarefas/buscar/usuario/2d3a712a-d85d-4618-838f-c77fcc7b9bf8

#### Listar usuario

GET http://localhost:5218/ListaDeTarefas/listar/usuario

#### Alterar usuario
 
PUT http://localhost:5218/ListaDeTarefas/alterar/usuario/2d3a712a-d85d-4618-838f-c77fcc7b9bf8
Content-Type: application/json

{
    "nome" : "Troca",
    "cpf"  : "188.922.000.92",
    "genero" : "feminino",
    "email"  : "Adrian@gmail.com"
}

#### Deletar usuario
DELETE http://localhost:5218/ListaDeTarefas/deletar/usuario/2d3a712a-d85d-4618-838f-c77fcc7b9bf8